### ISSUE TITLE
Having problem in  windows

### ISSUE THREAD

**Issue by Tilovefa** [leo-labs/vscode-dotnet#4]
Hi, 
When I was trying to use your extension in Windows. I found the dotnet new commands raised an error.
The input path started with a '/' which cause error in windows.
![image](https://user-images.githubusercontent.com/12470613/79527692-d419c900-809a-11ea-8fb5-b4d2a95b0b32.png)

**Comment by leo-labs** [comment]
Can you check if it is fixed?

**Comment by Tilovefa** [comment]
It works!

**Comment by Tilovefa** [comment]
> Can you check if it is fixed?

It works!

**Comment by Tilovefa** [comment]
> Can you check if it is fixed?

It works at dotnet new sth. process. But other processes still have the same bug to fix. e.g. dotnet sln add
![image](https://user-images.githubusercontent.com/12470613/80992624-5e6c7600-8e6c-11ea-99d5-f280831c2c5d.png)

**Comment by leo-labs** [comment]
Should be fixed now. Would you mind checking again?

**Comment by Tilovefa** [comment]
It works! Nice work. Tks.

**Comment by leo-labs** [comment]
Great! Thanks for testing and reporting this issue.

Let me know, if you have any other suggestions for improvement!
